# Generated by Django 4.2.4 on 2023-09-18 06:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_alter_order_date_alter_order_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 18, 11, 57, 54, 561499)),
        ),
    ]
